AWSTemplateFormatVersion: '2010-09-09'
Description: 'GuardQuote Backend - EC2 with Bun + Hono'

Parameters:
  Environment:
    Type: String
    Default: demo

  NetworkStackName:
    Type: String
    Default: guardquote-network
    Description: Name of the network stack

  InstanceType:
    Type: String
    Default: t3.small
    AllowedValues: [t3.micro, t3.small, t3.medium]

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 Key Pair for SSH access

  DbHost:
    Type: String
    Default: '192.168.2.70'
    Description: PostgreSQL host (Pi1 or RDS)

  DbPassword:
    Type: String
    NoEcho: true
    Description: Database password

  RedisHost:
    Type: String
    Default: '192.168.2.70'
    Description: Redis host

  RedisPassword:
    Type: String
    NoEcho: true
    Description: Redis password

  JwtSecret:
    Type: String
    NoEcho: true
    Description: JWT signing secret

Resources:
  # ============================================
  # IAM ROLE FOR EC2
  # ============================================
  BackendRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'guardquote-${Environment}-backend-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy

  BackendInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref BackendRole

  # ============================================
  # EC2 INSTANCE
  # ============================================
  BackendInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64}}'
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref BackendInstanceProfile
      SubnetId:
        Fn::ImportValue: !Sub '${NetworkStackName}-PublicSubnet1Id'
      SecurityGroupIds:
        - Fn::ImportValue: !Sub '${NetworkStackName}-AppSecurityGroupId'
      Tags:
        - Key: Name
          Value: !Sub 'guardquote-${Environment}-backend'

      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e

          # Update system
          dnf update -y
          dnf install -y git curl

          # Install Bun
          curl -fsSL https://bun.sh/install | bash
          export BUN_INSTALL="/root/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"

          # Clone repository
          cd /opt
          git clone https://github.com/jag18729/guard-quote.git
          cd guard-quote/backend

          # Create environment file
          cat > .env << 'EOF'
          NODE_ENV=production
          PORT=3000
          DATABASE_URL=postgresql://guardquote:${DbPassword}@${DbHost}:5432/guardquote
          REDIS_HOST=${RedisHost}
          REDIS_PASSWORD=${RedisPassword}
          JWT_SECRET=${JwtSecret}
          ML_ENGINE_URL=http://localhost:8000
          ML_ENGINE_SECRET=guardquote_s2s_secret_2026
          EOF

          # Install dependencies
          $BUN_INSTALL/bin/bun install

          # Create systemd service
          cat > /etc/systemd/system/guardquote-backend.service << 'EOF'
          [Unit]
          Description=GuardQuote Backend API
          After=network.target

          [Service]
          Type=simple
          User=root
          WorkingDirectory=/opt/guard-quote/backend
          Environment=PATH=/root/.bun/bin:/usr/local/bin:/usr/bin:/bin
          ExecStart=/root/.bun/bin/bun run src/index.ts
          Restart=always
          RestartSec=10

          [Install]
          WantedBy=multi-user.target
          EOF

          # Start service
          systemctl daemon-reload
          systemctl enable guardquote-backend
          systemctl start guardquote-backend

          # Signal success
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource BackendInstance --region ${AWS::Region}

    CreationPolicy:
      ResourceSignal:
        Timeout: PT10M

  # ============================================
  # ELASTIC IP
  # ============================================
  BackendEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref BackendInstance
      Tags:
        - Key: Name
          Value: !Sub 'guardquote-${Environment}-backend-eip'

  # ============================================
  # APPLICATION LOAD BALANCER (Optional)
  # ============================================
  # Uncomment for production with multiple instances
  # BackendALB:
  #   Type: AWS::ElasticLoadBalancingV2::LoadBalancer
  #   Properties:
  #     Name: !Sub 'guardquote-${Environment}-alb'
  #     Subnets:
  #       - Fn::ImportValue: !Sub '${NetworkStackName}-PublicSubnet1Id'
  #       - Fn::ImportValue: !Sub '${NetworkStackName}-PublicSubnet2Id'
  #     SecurityGroups:
  #       - Fn::ImportValue: !Sub '${NetworkStackName}-WebSecurityGroupId'

Outputs:
  InstanceId:
    Description: Backend EC2 Instance ID
    Value: !Ref BackendInstance

  PublicIP:
    Description: Backend Public IP
    Value: !Ref BackendEIP

  BackendUrl:
    Description: Backend API URL
    Value: !Sub 'http://${BackendEIP}:3000'

  SSHCommand:
    Description: SSH command
    Value: !Sub 'ssh -i ${KeyName}.pem ec2-user@${BackendEIP}'
