AWSTemplateFormatVersion: '2010-09-09'
Description: 'GuardQuote Frontend - S3 + CloudFront'

Parameters:
  Environment:
    Type: String
    Default: demo

  DomainName:
    Type: String
    Default: ''
    Description: Custom domain (leave empty for CloudFront default)

Resources:
  # ============================================
  # S3 BUCKET (Static Site Hosting)
  # ============================================
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'guardquote-${Environment}-frontend-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html  # SPA routing
      Tags:
        - Key: Name
          Value: !Sub 'guardquote-${Environment}-frontend'

  # ============================================
  # CLOUDFRONT ORIGIN ACCESS IDENTITY
  # ============================================
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'OAI for guardquote-${Environment}'

  # ============================================
  # S3 BUCKET POLICY (CloudFront Access)
  # ============================================
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudFrontOAI.S3CanonicalUserId
            Action: s3:GetObject
            Resource: !Sub '${FrontendBucket.Arn}/*'

  # ============================================
  # CLOUDFRONT DISTRIBUTION
  # ============================================
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Comment: !Sub 'GuardQuote ${Environment} Frontend'

        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOAI}'

        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD]
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          # Cache for 1 hour, revalidate
          DefaultTTL: 3600
          MaxTTL: 86400
          MinTTL: 0

        # SPA Routing - Return index.html for 404s
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 0
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 0

        PriceClass: PriceClass_100  # US, Canada, Europe only (cheapest)

        HttpVersion: http2

      Tags:
        - Key: Name
          Value: !Sub 'guardquote-${Environment}-cdn'

Outputs:
  BucketName:
    Description: S3 bucket for frontend files
    Value: !Ref FrontendBucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'

  CloudFrontDistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub '${AWS::StackName}-DistributionId'

  CloudFrontDomainName:
    Description: CloudFront Domain Name
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-DomainName'

  FrontendUrl:
    Description: Frontend URL
    Value: !Sub 'https://${CloudFrontDistribution.DomainName}'
