AWSTemplateFormatVersion: '2010-09-09'
Description: 'GuardQuote LDAP Server - OpenLDAP on EC2'

Parameters:
  Environment:
    Type: String
    Default: demo

  NetworkStackName:
    Type: String
    Default: guardquote-network

  InstanceType:
    Type: String
    Default: t3.micro

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 Key Pair for SSH access

  LdapAdminPassword:
    Type: String
    NoEcho: true
    Description: LDAP admin password
    MinLength: 8

  LdapDomain:
    Type: String
    Default: 'guardquote.local'
    Description: LDAP domain (e.g., guardquote.local)

Resources:
  # ============================================
  # EC2 INSTANCE (OpenLDAP)
  # ============================================
  LdapInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64}}'
      KeyName: !Ref KeyName
      SubnetId:
        Fn::ImportValue: !Sub '${NetworkStackName}-PrivateSubnet1Id'
      SecurityGroupIds:
        - Fn::ImportValue: !Sub '${NetworkStackName}-LdapSecurityGroupId'
      Tags:
        - Key: Name
          Value: !Sub 'guardquote-${Environment}-ldap'

      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e

          # Update system
          dnf update -y

          # Install OpenLDAP
          dnf install -y openldap-servers openldap-clients

          # Start slapd
          systemctl start slapd
          systemctl enable slapd

          # Set admin password
          LDAP_ADMIN_PW=$(slappasswd -s "${LdapAdminPassword}")

          # Configure root DN password
          cat > /tmp/rootpw.ldif << EOF
          dn: olcDatabase={0}config,cn=config
          changetype: modify
          add: olcRootPW
          olcRootPW: $LDAP_ADMIN_PW
          EOF
          ldapmodify -Y EXTERNAL -H ldapi:/// -f /tmp/rootpw.ldif

          # Configure domain
          LDAP_SUFFIX=$(echo "${LdapDomain}" | sed 's/\./,dc=/g' | sed 's/^/dc=/')

          cat > /tmp/domain.ldif << EOF
          dn: olcDatabase={1}mdb,cn=config
          changetype: modify
          replace: olcSuffix
          olcSuffix: $LDAP_SUFFIX
          -
          replace: olcRootDN
          olcRootDN: cn=admin,$LDAP_SUFFIX
          -
          add: olcRootPW
          olcRootPW: $LDAP_ADMIN_PW
          EOF
          ldapmodify -Y EXTERNAL -H ldapi:/// -f /tmp/domain.ldif

          # Create base structure
          cat > /tmp/base.ldif << EOF
          dn: $LDAP_SUFFIX
          objectClass: top
          objectClass: dcObject
          objectClass: organization
          o: GuardQuote
          dc: $(echo "${LdapDomain}" | cut -d. -f1)

          dn: ou=users,$LDAP_SUFFIX
          objectClass: organizationalUnit
          ou: users

          dn: ou=groups,$LDAP_SUFFIX
          objectClass: organizationalUnit
          ou: groups

          dn: cn=admins,ou=groups,$LDAP_SUFFIX
          objectClass: groupOfNames
          cn: admins
          member: cn=admin,$LDAP_SUFFIX

          dn: cn=users,ou=groups,$LDAP_SUFFIX
          objectClass: groupOfNames
          cn: users
          member: cn=admin,$LDAP_SUFFIX
          EOF
          ldapadd -x -D "cn=admin,$LDAP_SUFFIX" -w "${LdapAdminPassword}" -f /tmp/base.ldif

          # Create demo users
          cat > /tmp/users.ldif << EOF
          dn: uid=demo.admin,ou=users,$LDAP_SUFFIX
          objectClass: inetOrgPerson
          objectClass: posixAccount
          objectClass: shadowAccount
          cn: Demo Admin
          sn: Admin
          givenName: Demo
          uid: demo.admin
          uidNumber: 1001
          gidNumber: 1001
          homeDirectory: /home/demo.admin
          loginShell: /bin/bash
          userPassword: $(slappasswd -s "admin123")
          mail: demo.admin@guardquote.local

          dn: uid=demo.user,ou=users,$LDAP_SUFFIX
          objectClass: inetOrgPerson
          objectClass: posixAccount
          objectClass: shadowAccount
          cn: Demo User
          sn: User
          givenName: Demo
          uid: demo.user
          uidNumber: 1002
          gidNumber: 1002
          homeDirectory: /home/demo.user
          loginShell: /bin/bash
          userPassword: $(slappasswd -s "user123")
          mail: demo.user@guardquote.local
          EOF
          ldapadd -x -D "cn=admin,$LDAP_SUFFIX" -w "${LdapAdminPassword}" -f /tmp/users.ldif

          # Cleanup
          rm -f /tmp/*.ldif

          # Signal success
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource LdapInstance --region ${AWS::Region}

    CreationPolicy:
      ResourceSignal:
        Timeout: PT10M

Outputs:
  InstanceId:
    Description: LDAP Instance ID
    Value: !Ref LdapInstance

  PrivateIP:
    Description: LDAP Private IP
    Value: !GetAtt LdapInstance.PrivateIp

  LdapUrl:
    Description: LDAP URL (internal)
    Value: !Sub 'ldap://${LdapInstance.PrivateIp}:389'

  LdapBaseDN:
    Description: LDAP Base DN
    Value: !Sub 'dc=${LdapDomain}'

  LdapAdminDN:
    Description: LDAP Admin DN
    Value: !Sub 'cn=admin,dc=${LdapDomain}'

  DemoUsers:
    Description: Demo user credentials
    Value: 'demo.admin/admin123, demo.user/user123'
